### PR TITLE
Add support for output file of the full lint

### PR DESCRIPTION
**Pull request by sciffer**
Add support for output file of the full lint

### CODE REVIEW

**Comment by earonesty** [comment]
LGTM, please try to get lint + coverage to pass

**Comment by earonesty** [comment]
need to add a test to fix the coverage issues.  ie: this option isn't tested.

**Comment by sciffer** [comment]
Added a test, but it seems that other test are breaking all of the
sudden(it pass on one platform bat fails on other). The tests that fail are
not related to the code change I made.

**Comment by sciffer** [comment]
Never mind, it's fixed now all tests are passing. Where do you see coverage?

**Comment by earonesty** [comment]
Ok, this is cool, but I'm uncertain how useful it is, since we don't run lint on all the files.... only the ones that have changed.   It might make more sense to write the file after filtering - that way if you have downstream tools, they can use it.

**Pull request closed without merging**
